[
    {
        "id": 0,
        "date": "Thu, 19/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-19T17:30:00",
        "title": "ΜΙΚΡΕΣ ΙΣΤΟΡΙΕΣ",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 1,
        "date": "Thu, 19/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-19T18:00:00",
        "title": "ΔΙΑΚΡΙΤΙΚΟΣ ΦΩΤΙΣΜΟΣ / INTIMATE LIGHTING / INTIMNÍ OSVETLENÍ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 2,
        "date": "Thu, 19/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-19T18:00:00",
        "title": "ΕΛΛΗΝΙΚΕΣ ΜΙΚΡΕΣ ΙΣΤΟΡΙΕΣ - ΔΙΑΓΩΝΙΣΤΙΚΟ Α’",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 3,
        "date": "Thu, 19/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-19T18:00:00",
        "title": "ΑΜΥΓΔΑΛΙΑ / AMYGDALIÁ | PORTRAITS ",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 4,
        "date": "Thu, 19/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-19T19:00:00",
        "title": "ΧΟΡΟΓΡΑΦΩΝΤΑΣ ΤΗΝ ΗΧΩ / CRAFTING AN ECHO",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 5,
        "date": "Thu, 19/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-19T19:45:00",
        "title": "ΜΙΑ ΑΠΟΙΚΙΑ / A COLONY / UNE COLONIE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 6,
        "date": "Thu, 19/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-19T19:45:00",
        "title": "Η ΑΝΑΣΑ / THE BREATH / DER ATEM",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 7,
        "date": "Thu, 19/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-19T20:00:00",
        "title": "ΤΟ ΕΘΝΟΣ ΤΟΥ ΕΝΟΣ ΠΑΙΔΙΟΥ / ONE CHILD NATION",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 8,
        "date": "Thu, 19/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-19T20:30:00",
        "title": "ADORATION / ΠΑΡΑΦΟΡΗ ΛΑΤΡΕΙΑ",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 9,
        "date": "Thu, 19/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-19T21:00:00",
        "title": "THE CHILLS: Ο ΘΡΙΑΜΒΟΣ ΚΑΙ Η ΤΡΑΓΩΔΙΑ ΤΟΥ ΜΑΡΤΙΝ ΦΙΛΙΠΣ / THE CHILLS: THE TRIUMPH & TRAGEDY OF MARTIN PHILLIPPS",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 10,
        "date": "Thu, 19/9",
        "time": "21:15",
        "director": "director goes here",
        "datetime": "1900-09-19T21:15:00",
        "title": "ΜΕΧΡΙ ΤΗ ΘΑΛΑΣΣΑ / AS FAR AS THE SEA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 11,
        "date": "Thu, 19/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-19T22:00:00",
        "title": "ΜΟΝΟ ΘΡΑΣ / MURDER IN THE FRONT ROW: THE SAN FRANCISCO BAY AREA THRASH METAL STORY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 12,
        "date": "Thu, 19/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-19T22:00:00",
        "title": "ΠΑΡΑΣΙΤΑ / PARASITE / GISAENGCHUNG",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 13,
        "date": "Thu, 19/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-19T22:15:00",
        "title": "ΤΟ ΧΡΥΣΟ ΓΑΝΤΙ / THE GOLDEN GLOVE / DER GOLDENE HANDSCHUH",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 14,
        "date": "Thu, 19/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-19T22:30:00",
        "title": "MONSOON / ΜΟΥΣΩΝΑΣ",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 15,
        "date": "Fri, 20/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-20T18:00:00",
        "title": "ΤΟ ΑΣΤΕΙΟ / THE JOKE / ZERT",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 16,
        "date": "Fri, 20/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-20T18:00:00",
        "title": "Η ΟΙΚΟΓΕΝΕΙΑ ΤΟΥ ΜΕΣΟΝΥΧΤΙΟΥ / MIDNIGHT FAMILY",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 17,
        "date": "Fri, 20/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-20T18:00:00",
        "title": "ΕΛΛΗΝΙΚΕΣ ΜΙΚΡΕΣ ΙΣΤΟΡΙΕΣ - ΔΙΑΓΩΝΙΣΤΙΚΟ Β’",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 18,
        "date": "Fri, 20/9",
        "time": "18:30",
        "director": "director goes here",
        "datetime": "1900-09-20T18:30:00",
        "title": "ΟΙ ΕΡΩΤΕΣ ΜΙΑΣ ΞΑΝΘΙΑΣ / LOVES OF A BLONDE / LASKY JEDNE PLAVOVLASKY",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 19,
        "date": "Fri, 20/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-20T19:00:00",
        "title": "ΤΟ ΕΘΝΟΣ ΤΟΥ ΕΝΟΣ ΠΑΙΔΙΟΥ / ONE CHILD NATION",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 20,
        "date": "Fri, 20/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-20T19:00:00",
        "title": "ΜΙΑ ΑΠΟΙΚΙΑ / A COLONY / UNE COLONIE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 21,
        "date": "Fri, 20/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-20T20:00:00",
        "title": "ΥΒ ΣΕΝ ΛΟΡΑΝ: ΥΣΤΕΡΟΓΡΑΦΟ / CELEBRATION",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 22,
        "date": "Fri, 20/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-20T20:00:00",
        "title": "ΝΕΑ ΛΙΘΟΥΑΝΙΑ / NOVA LITUANIA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 23,
        "date": "Fri, 20/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-20T20:00:00",
        "title": "MILES DAVIS: BIRTH OF THE COOL",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 24,
        "date": "Fri, 20/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-20T20:30:00",
        "title": "ΚΑΙ ΕΝΑ…ΚΑΙ ΔΥΟ…ΟΙΚΟΓΕΝΕΙΑΚΟΙ ΡΥΘΜΟΙ / ΥΙ ΥΙ / YI YI: A ONE AND A TWO...",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 25,
        "date": "Fri, 20/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-20T21:00:00",
        "title": "ΜΙΚΡΕΣ ΙΣΤΟΡΙΕΣ (Ε)",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 26,
        "date": "Fri, 20/9",
        "time": "21:30",
        "director": "director goes here",
        "datetime": "1900-09-20T21:30:00",
        "title": "ΜΟΥΣΩΝΑΣ / MONSOON",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 27,
        "date": "Fri, 20/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-20T22:00:00",
        "title": "ΤΟ ΣΠΙΤΙ ΤΟΥ ΜΙΚΡΟΥ ΠΤΗΝΟΥ / HOUSE OF HUMMINGBIRD / BEOL-SAE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 28,
        "date": "Fri, 20/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-20T22:15:00",
        "title": "ΕΠΟΥΡΑΝΙΑ ΑΓΑΠΗ / DIVINE LOVE / DIVINO AMOR",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 29,
        "date": "Fri, 20/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-20T22:30:00",
        "title": "ΦΩΣ ΣΤΟ ΣΚΟΤΑΔΙ / LIGHT OF MY LIFE",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 30,
        "date": "Sat, 21/9",
        "time": "17:15",
        "director": "director goes here",
        "datetime": "1900-09-21T17:15:00",
        "title": "Η ΣΥΓΧΥΣΗ ΤΟΥ ΚΟΜΦΟΥΚΙΟΥ / A CONFUCIAN CONFUSION / DU LI SHI DAI",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 31,
        "date": "Sat, 21/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-21T18:00:00",
        "title": "Ο ΥΠΕΡΟΧΟΣ ΒΑΡΟΝΟΣ ΜΙΝΧΑΟΥΖΕΝ / THE FABULOUS BARON MUNCHAUSEN / BARON PRASIL",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 32,
        "date": "Sat, 21/9",
        "time": "18:15",
        "director": "director goes here",
        "datetime": "1900-09-21T18:15:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Γ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 33,
        "date": "Sat, 21/9",
        "time": "18:30",
        "director": "director goes here",
        "datetime": "1900-09-21T18:30:00",
        "title": "ΤΑ ΧΡΟΝΙΚΑ ΤΗΣ ΜΑΡΙΟΝ ΣΤΟΟΥΚΣ / RECORDER: THE MARION STOKES PROJECT",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 34,
        "date": "Sat, 21/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-21T19:00:00",
        "title": "ΜΟΝΟ ΘΡΑΣ / MURDER IN THE FRONT ROW: THE SAN FRANCISCO BAY AREA THRASH METAL STORY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 35,
        "date": "Sat, 21/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-21T19:00:00",
        "title": "ΝΕΑ ΛΙΘΟΥΑΝΙΑ / NOVA LITUANIA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 36,
        "date": "Sat, 21/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-21T20:00:00",
        "title": "Ο ΜΠΟΥΝΙΟΥΕΛ ΣΤΟ ΛΑΒΥΡΙΝΘΟ ΜΕ ΤΙΣ ΧΕΛΩΝΕΣ / BUNUEL IN THE LABYRINTH OF THE TURTLES / BUNUEL EN EL LABERINTO DE LAS TORTU",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 37,
        "date": "Sat, 21/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-21T20:00:00",
        "title": "Η ΓΗ ΤΟΥ ΜΕΛΙΤΟΣ / HONEYLAND ",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 38,
        "date": "Sat, 21/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-21T20:30:00",
        "title": "ΑΓΟΥΡΟΣ ΕΡΩΤΑΣ / PREMATURE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 39,
        "date": "Sat, 21/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-21T20:30:00",
        "title": "BLINDED BY THE LIGHT",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 40,
        "date": "Sat, 21/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-21T21:00:00",
        "title": "Η ΟΙΚΟΓΕΝΕΙΑ ΤΟΥ ΜΕΣΟΝΥΧΤΙΟΥ / MIDNIGHT FAMILY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 41,
        "date": "Sat, 21/9",
        "time": "21:15",
        "director": "director goes here",
        "datetime": "1900-09-21T21:15:00",
        "title": "ΤΟ ΣΠΙΤΙ ΤΟΥ ΜΙΚΡΟΥ ΠΤΗΝΟΥ / HOUSE OF HUMMINGBIRD / BEOL-SAE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 42,
        "date": "Sat, 21/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-21T22:00:00",
        "title": "Η ΜΕΓΑΛΗ ΝΥΧΤΑ ΤΗΣ ΝΑΠΟΛΗΣ / PIRANHAS / LA PARANZA DEI BAMBINI",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 43,
        "date": "Sat, 21/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-21T22:00:00",
        "title": "ΜΙΑ ΛΕΥΚΗ, ΛΕΥΚΗ ΜΕΡΑ / A WHITE, WHITE DAY / HVITUR, HVITUR DAGUR",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 44,
        "date": "Sat, 21/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-21T22:30:00",
        "title": "ΕΔΩ ΔΕΝ ΕΙΝΑΙ ΒΕΡΟΛΙΝΟ / THIS IS NOT BERLIN / ESTO NO ES BERLIN",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 45,
        "date": "Sat, 21/9",
        "time": "23:00",
        "director": "director goes here",
        "datetime": "1900-09-21T23:00:00",
        "title": "Η ΕΚΣΤΑΣΗ ΤΟΥ ΑΙΜΑΤΟΣ / BLISS",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 46,
        "date": "Wed, 18/9",
        "time": "12:00",
        "director": "director goes here",
        "datetime": "1900-09-18T12:00:00",
        "title": "Εισιτήρια Διαρκείας: 5 Προβολών ",
        "subtitle": "subtitle goes here",
        "room": "Νύχτες Πρεμιέρας  - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 47,
        "date": "Sun, 22/9",
        "time": "17:00",
        "director": "director goes here",
        "datetime": "1900-09-22T17:00:00",
        "title": "ΝΕΚΡΑ ΠΟΥΛΙΑ / DEAD BIRDS",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 48,
        "date": "Sun, 22/9",
        "time": "17:15",
        "director": "director goes here",
        "datetime": "1900-09-22T17:15:00",
        "title": "ΤΟ ΠΑΘΟΣ ΤΗΣ ΑΝΝΑ ΜΑΝΙΑΝΙ / THE PASSION OF ANNA MAGNANI / LA PASSIONE DI ANNA MAGNANI | Η ΑΓΑΠΗ / L'AMORE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 49,
        "date": "Sun, 22/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-22T18:00:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Δ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 50,
        "date": "Sun, 22/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-22T18:00:00",
        "title": "AMAZING GRACE",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 51,
        "date": "Sun, 22/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-22T19:00:00",
        "title": "ΟΙ ΕΡΩΤΕΣ ΜΙΑΣ ΞΑΝΘΙΑΣ / LOVES OF A BLONDE / LASKY JEDNE PLAVOVLASKY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 52,
        "date": "Sun, 22/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-22T19:00:00",
        "title": "ΣΥΝΩΝΥΜΑ / SYNONYMS / SYNONYMES",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 53,
        "date": "Sun, 22/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-22T20:00:00",
        "title": "ΦΩΤΙΑ ΣΤΗ ΛΟΥΙΖΙΑΝΑ / BURNING CANE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 54,
        "date": "Sun, 22/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-22T20:00:00",
        "title": "ΟΙΚΟΓΕΝΕΙΑΚΗ ΕΥΤΥΧΙΑ Α.Ε. / FAMILY ROMANCE LLC",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 55,
        "date": "Sun, 22/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-22T20:00:00",
        "title": "ΜΙΑ ΛΑΜΠΡΟΤΕΡΗ ΚΑΛΟΚΑΙΡΙΝΗ ΜΕΡΑ / A BRIGHTER SUMMER DAY / GU LING JIE SHAO NIAN SHA REN SHI JIAN",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 56,
        "date": "Sun, 22/9",
        "time": "20:15",
        "director": "director goes here",
        "datetime": "1900-09-22T20:15:00",
        "title": "ΑΠΟΛΙΘΩΜΑΤΑ / FOSSILS",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 57,
        "date": "Sun, 22/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-22T21:00:00",
        "title": "ΤΑ ΧΡΟΝΙΚΑ ΤΗΣ ΜΑΡΙΟΝ ΣΤΟΟΥΚΣ / RECORDER: THE MARION STOKES PROJECT",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 58,
        "date": "Sun, 22/9",
        "time": "21:30",
        "director": "director goes here",
        "datetime": "1900-09-22T21:30:00",
        "title": "ΔΙΑΚΡΙΤΙΚΟΣ ΦΩΤΙΣΜΟΣ / INTIMATE LIGHTING / INTIMNÍ OSVETLENÍ",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 59,
        "date": "Sun, 22/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-22T22:00:00",
        "title": "ΤΖΕΖΕΜΠΕΛ / JEZEBEL",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 60,
        "date": "Sun, 22/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-22T22:00:00",
        "title": "ΜΑΡΙΓΚΕΛΑ, Ο ΕΠΑΝΑΣΤΑΤΗΣ / MARIGHELLA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 61,
        "date": "Sun, 22/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-22T22:00:00",
        "title": "ΜΙΑ ΛΕΥΚΗ, ΛΕΥΚΗ ΜΕΡΑ / A WHITE, WHITE DAY / HVITUR, HVITUR DAGUR",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 62,
        "date": "Mon, 23/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-23T17:30:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Ε",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 63,
        "date": "Mon, 23/9",
        "time": "17:45",
        "director": "director goes here",
        "datetime": "1900-09-23T17:45:00",
        "title": "Η ΑΝΑΦΟΡΑ ΓΙΑ ΤΟ ΠΑΡΤΙ ΚΑΙ ΤΟΥΣ ΚΑΛΕΣΜΕΝΟΥΣ / A REPORT ON THE PARTY AND GUESTS / O SLAVNOSTI A HOSTECH",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 64,
        "date": "Mon, 23/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-23T18:00:00",
        "title": "ΑΓΟΥΡΟΣ ΕΡΩΤΑΣ / PREMATURE",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 65,
        "date": "Mon, 23/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-23T19:00:00",
        "title": "ΜΟΥΣΩΝΑΣ / MONSOON",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 66,
        "date": "Mon, 23/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-23T19:00:00",
        "title": "THE CHILLS: Ο ΘΡΙΑΜΒΟΣ ΚΑΙ Η ΤΡΑΓΩΔΙΑ ΤΟΥ ΜΑΡΤΙΝ ΦΙΛΙΠΣ / THE CHILLS: THE TRIUMPH & TRAGEDY OF MARTIN PHILLIPPS",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 67,
        "date": "Mon, 23/9",
        "time": "19:15",
        "director": "director goes here",
        "datetime": "1900-09-23T19:15:00",
        "title": "ΡΟΥΖ / ROUGE | ΔΟΝΗΣΕΙΣ / TREMORS / TREMBLORES",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 68,
        "date": "Mon, 23/9",
        "time": "19:30",
        "director": "director goes here",
        "datetime": "1900-09-23T19:30:00",
        "title": "ΤΟ ΤΕΛΟΣ ΤΗΣ ΔΙΑΔΡΟΜΗΣ / END OF SENTENCE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 69,
        "date": "Mon, 23/9",
        "time": "19:30",
        "director": "director goes here",
        "datetime": "1900-09-23T19:30:00",
        "title": "ΡΑΜΜΑΤΑ / STITCHES / SAVOVI",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 70,
        "date": "Mon, 23/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-23T20:00:00",
        "title": "ΔΕΝΤΡΑ ΣΤΗΝ ΕΡΗΜΟ / TALKING ABOUT TREES",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 71,
        "date": "Mon, 23/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-23T21:00:00",
        "title": "ΕΔΩ ΔΕΝ ΕΙΝΑΙ ΒΕΡΟΛΙΝΟ / THIS IS NOT BERLIN / ESTO NO ES BERLIN",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 72,
        "date": "Mon, 23/9",
        "time": "21:15",
        "director": "director goes here",
        "datetime": "1900-09-23T21:15:00",
        "title": "ΠΑΡΑΦΟΡΗ ΛΑΤΡΕΙΑ / ADORATION",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 73,
        "date": "Mon, 23/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-23T22:00:00",
        "title": "TAIPEI STORY / QING MEI ZHU MA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 74,
        "date": "Mon, 23/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-23T22:00:00",
        "title": "ΔΥΣΤΥΧΩΣ ΑΠΟΥΣΙΑΖΑΤΕ / SORRY WE MISSED YOUSORRY WE MISSED YOU",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 75,
        "date": "Mon, 23/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-23T22:00:00",
        "title": "ΣΥΝΩΝΥΜΑ / SYNONYMS / SYNONYMES",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 76,
        "date": "Mon, 23/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-23T22:00:00",
        "title": "NIMIC | Ο ΑΠΟΤΕΦΡΩΤΗΣ / THE CREMATOR / SPALOVAC MRTVOL",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 77,
        "date": "Tue, 24/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-24T17:30:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ ΣΤ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 78,
        "date": "Tue, 24/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-24T17:30:00",
        "title": "Ο ΑΝΘΡΩΠΟΣ ΠΟΥ ΕΒΛΕΠΕ ΤΑ ΤΡΕΝΑ ΝΑ ΠΕΡΝΟΥΝ / CLOSELY WATCHED TRAINS / OSTRE SLEDOVANE VLAKY",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 79,
        "date": "Tue, 24/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-24T17:30:00",
        "title": "ΜΑΓΙΟΝΓΚ / MAHJONG",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 80,
        "date": "Tue, 24/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-24T18:00:00",
        "title": "ΥΒ ΣΕΝ ΛΟΡΑΝ: ΥΣΤΕΡΟΓΡΑΦΟ / CELEBRATION",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 81,
        "date": "Tue, 24/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-24T19:00:00",
        "title": "ΔΕΝΤΡΑ ΣΤΗΝ ΕΡΗΜΟ / TALKING ABOUT TREES",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 82,
        "date": "Tue, 24/9",
        "time": "19:30",
        "director": "director goes here",
        "datetime": "1900-09-24T19:30:00",
        "title": "ΣΦΑΛΜΑ ΣΥΣΤΗΜΑΤΟΣ / SYSTEM CRASHER / SYSTEMSPRENGER",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 83,
        "date": "Tue, 24/9",
        "time": "19:30",
        "director": "director goes here",
        "datetime": "1900-09-24T19:30:00",
        "title": "ΤΡΥΦΕΡΟΣ ΑΠΟΧΑΙΡΕΤΙΣΜΟΣ / THE FAREWELL",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 84,
        "date": "Tue, 24/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-24T19:45:00",
        "title": "Η ΚΑΜΑΡΙΕΡΑ / THE CHAMBERMAID / LA CAMARISTA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 85,
        "date": "Tue, 24/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-24T19:45:00",
        "title": "ΤΟ ΑΣΤΕΙΟ / THE JOKE / ZERT",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 86,
        "date": "Tue, 24/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-24T20:00:00",
        "title": "ΔΥΣΤΥΧΩΣ ΑΠΟΥΣΙΑΖΑΤΕ / SORRY WE MISSED YOUSORRY WE MISSED YOU",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 87,
        "date": "Tue, 24/9",
        "time": "21:15",
        "director": "director goes here",
        "datetime": "1900-09-24T21:15:00",
        "title": "ΝΕΑ ΛΙΘΟΥΑΝΙΑ / NOVA LITUANIA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 88,
        "date": "Tue, 24/9",
        "time": "21:45",
        "director": "director goes here",
        "datetime": "1900-09-24T21:45:00",
        "title": "ΦΩΤΙΑ ΣΤΗ ΛΟΥΙΖΙΑΝΑ / BURNING CANE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 89,
        "date": "Tue, 24/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-24T22:00:00",
        "title": "ΤΑ 4 ΕΠΙΠΕΔΑ ΤΗΣ ΥΠΑΡΞΗΣ / THE 4 LEVELS OF EXISTENCE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 90,
        "date": "Tue, 24/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-24T22:00:00",
        "title": "ΛΕΩΦΟΡΟΣ ΠΑΤΗΣΙΩΝ / PATISION AVENUE | ΟΙ ΑΘΛΙΟΙ / LES MISERABLES",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 91,
        "date": "Tue, 24/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-24T22:15:00",
        "title": "Ο ΠΡΙΓΚΗΠΑΣ / THE PRINCE / EL PRINCIPE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 92,
        "date": "Tue, 24/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-24T22:30:00",
        "title": "ZOMBI CHILD ",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 93,
        "date": "Wed, 25/9",
        "time": "17:00",
        "director": "director goes here",
        "datetime": "1900-09-25T17:00:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Z",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 94,
        "date": "Wed, 25/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-25T17:30:00",
        "title": "Η ΚΟΙΛΑΔΑ ΜΕ ΤΙΣ ΜΕΛΙΣΣΕΣ / VALLEY OF THE BEES / UDOLI VCEL",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 95,
        "date": "Wed, 25/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-25T18:00:00",
        "title": "ΟΣΑ ΔΕΝ ΕΓΙΝΑΝ ΣΤΑΧΤΗ / LAND OF ASHES / CENIZA NEGRA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 96,
        "date": "Wed, 25/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-25T18:00:00",
        "title": "ΠΙΣΩ ΑΠΟ ΤΟΝ ΤΟΙΧΟ / BEHIND THE WALL",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 97,
        "date": "Wed, 25/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-25T19:00:00",
        "title": "ΡΑΜΜΑΤΑ / STITCHES / SAVOVI",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 98,
        "date": "Wed, 25/9",
        "time": "19:00",
        "director": "director goes here",
        "datetime": "1900-09-25T19:00:00",
        "title": "Η ΟΙΚΟΓΕΝΕΙΑ ΤΟΥ ΜΕΣΟΝΥΧΤΙΟΥ / MIDNIGHT FAMILY",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 99,
        "date": "Wed, 25/9",
        "time": "19:15",
        "director": "director goes here",
        "datetime": "1900-09-25T19:15:00",
        "title": "ΣΤΟ ΦΩΣ ΤΟΥ ΦΕΓΓΑΡΙΟΥ / MOONLIGHTING",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 100,
        "date": "Wed, 25/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-25T19:45:00",
        "title": "ΤΟ ΑΥΓΟ / ONDOG",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 101,
        "date": "Wed, 25/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-25T19:45:00",
        "title": "ΜΗΤΕΡΑ / MOTHER",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 102,
        "date": "Wed, 25/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-25T20:00:00",
        "title": "ΕΙΜΑΣΤΕ ΜΙΚΡΑ ΖΟΜΠΙ / WE ARE LITTLE ZOMBIES / WI A RITORU ZOMBIZU",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 103,
        "date": "Wed, 25/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-25T21:00:00",
        "title": "ΤΟ ΕΘΝΟΣ ΤΟΥ ΕΝΟΣ ΠΑΙΔΙΟΥ / ONE CHILD NATION",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 104,
        "date": "Wed, 25/9",
        "time": "21:15",
        "director": "director goes here",
        "datetime": "1900-09-25T21:15:00",
        "title": "ΔΟΝΗΣΕΙΣ / TREMORS / TREMBLORES",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 105,
        "date": "Wed, 25/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-25T22:00:00",
        "title": "Ο ΗΧΟΣ ΤΗΣ ΣΙΩΠΗΣ / THE SOUND OF SILENCE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 106,
        "date": "Wed, 25/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-25T22:00:00",
        "title": "ΟΙ ΤΡΟΜΟΚΡΑΤΕΣ / THE TERRORIZERS / KONG BU FEN ZI",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 107,
        "date": "Wed, 25/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-25T22:15:00",
        "title": "ΠΟΡΤΡΕΤΟ ΜΙΑΣ ΓΥΝΑΙΚΑΣ ΠΟΥ ΦΛΕΓΕΤΑΙ / PORTRAIT OF A LADY ON FIRE / PORTRAIT DE LA JEUNE FILLE EN FEU",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 108,
        "date": "Wed, 25/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-25T22:30:00",
        "title": "FIRST LOVE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 109,
        "date": "Thu, 26/9",
        "time": "17:15",
        "director": "director goes here",
        "datetime": "1900-09-26T17:15:00",
        "title": "Η ΑΠΙΘΑΝΗ ΙΣΤΟΡΙΑ ΤΟΥ ΜΑΓΟΥ ΤΖΟΝΑΘΑΝ / THE AMAZING JOHNATHAN DOCUMENTARY",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 110,
        "date": "Thu, 26/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-26T17:30:00",
        "title": "ΝΤΕΪΒΙΝΤ ΚΡΟΣΜΠΙ: ΝΑ ΘΥΜΑΣΑΙ ΤΟ ΟΝΟΜΑ ΜΟΥ / DAVID CROSBY: REMEMBER MY NAME",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 111,
        "date": "Thu, 26/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-26T17:30:00",
        "title": "Η ΚΟΙΛΑΔΑ ΜΕ ΤΙΣ ΜΕΛΙΣΣΕΣ / VALLEY OF THE BEES / UDOLI VCEL",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 112,
        "date": "Thu, 26/9",
        "time": "17:45",
        "director": "director goes here",
        "datetime": "1900-09-26T17:45:00",
        "title": "Ο ΑΝΘΡΩΠΟΣ ΠΟΥ ΕΒΛΕΠΕ ΤΑ ΤΡΕΝΑ ΝΑ ΠΕΡΝΟΥΝ / CLOSELY WATCHED TRAINS / OSTRE SLEDOVANE VLAKY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 113,
        "date": "Thu, 26/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-26T18:00:00",
        "title": "...ΚΑΙ Ο ΠΕΜΠΤΟΣ ΚΑΒΑΛΑΡΗΣ ΕΙΝΑΙ Ο ΦΟΒΟΣ / ...AND THE FIFTH HORSEMAN IS FEAR / ...A PATY JEZDEC JE STRACH",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 114,
        "date": "Thu, 26/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-26T18:00:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Η",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 115,
        "date": "Thu, 26/9",
        "time": "19:15",
        "director": "director goes here",
        "datetime": "1900-09-26T19:15:00",
        "title": "ΧΑΛΣΤΟΝ, Ο ΑΝΘΡΩΠΟΣ ΠΟΥ ΚΕΝΤΗΣΕ ΜΙΑ ΑΥΤΟΚΡΑΤΟΡΙΑ / HALSTON",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 116,
        "date": "Thu, 26/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-26T19:45:00",
        "title": "MUSIC FOR ORDINARY LIFE MACHINES",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 117,
        "date": "Thu, 26/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-26T19:45:00",
        "title": "Η ΚΑΜΑΡΙΕΡΑ / THE CHAMBERMAID / LA CAMARISTA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 118,
        "date": "Thu, 26/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-26T20:00:00",
        "title": "ΟΙ ΑΘΛΙΟΙ / LES MISERABLES",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 119,
        "date": "Thu, 26/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-26T20:00:00",
        "title": "ΣΤΗ ΛΙΜΝΗ ΜΕ ΤΙΣ ΑΓΡΙΕΣ ΧΗΝΕΣ / THE WILD GOOSE LAKE / NAN FANG CHE ZHAN DE JU HUI",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 120,
        "date": "Thu, 26/9",
        "time": "20:15",
        "director": "director goes here",
        "datetime": "1900-09-26T20:15:00",
        "title": "Η ΟΡΟΣΕΙΡΑ ΤΩΝ ΟΝΕΙΡΩΝ / THE CORDILLERA OF DREAMS / LA CORDILLERA DE LOS SUENOS",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 121,
        "date": "Thu, 26/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-26T22:15:00",
        "title": "ΜΙΑ ΑΠΟΙΚΙΑ / A COLONY / UNE COLONIE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 122,
        "date": "Thu, 26/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-26T22:15:00",
        "title": "ΟΙ ΚΑΡΧΑΡΙΕΣ / THE SHARKS / LOS TIBURONES",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 123,
        "date": "Thu, 26/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-26T22:15:00",
        "title": "ΣΟΛΕ / SOLE",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 124,
        "date": "Thu, 26/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-26T22:30:00",
        "title": "REPO MAN",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 125,
        "date": "Thu, 26/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-26T22:30:00",
        "title": "ΟΣΑ ΔΕΝ ΕΓΙΝΑΝ ΣΤΑΧΤΗ / LAND OF ASHES / CENIZA NEGRA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 126,
        "date": "Thu, 26/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-26T22:30:00",
        "title": "ΡΟΖ ΤΕΙΧΟΣ / PINK WALL",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 127,
        "date": "Fri, 27/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-27T17:30:00",
        "title": "Ελληνικές Μικρές Ιστορίες - ΔΙΑΓΩΝΙΣΤΙΚΟ Θ",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 128,
        "date": "Fri, 27/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-27T18:00:00",
        "title": "THE CHILLS: Ο ΘΡΙΑΜΒΟΣ ΚΑΙ Η ΤΡΑΓΩΔΙΑ ΤΟΥ ΜΑΡΤΙΝ ΦΙΛΙΠΣ / THE CHILLS: THE TRIUMPH & TRAGEDY OF MARTIN PHILLIPPS",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 129,
        "date": "Fri, 27/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-27T18:00:00",
        "title": "Η ΚΑΜΑΡΙΕΡΑ / THE CHAMBERMAID / LA CAMARISTA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 130,
        "date": "Fri, 27/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-27T18:00:00",
        "title": "Η ΓΗ ΤΟΥ ΜΕΛΙΤΟΣ / HONEYLAND ",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 131,
        "date": "Fri, 27/9",
        "time": "18:30",
        "director": "director goes here",
        "datetime": "1900-09-27T18:30:00",
        "title": "ΠΑΙΧΝΙΔΙΑ ΤΗΣ ΤΥΧΗΣ / SERENDIPITY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 132,
        "date": "Fri, 27/9",
        "time": "19:15",
        "director": "director goes here",
        "datetime": "1900-09-27T19:15:00",
        "title": "ΑΠΟΝΟΜΗ ΒΡΑΒΕΙΩΝ ΠΡΩΤΟΕΜΦΑΝΙΖΟΜΕΝΩΝ ΔΗΜΙΟΥΡΓΩΝ ΚΑΙ ΗΘΟΠΟΙΩΝ ΕΛΛΗΝΙΚΩΝ ΤΑΙΝΙΩΝ ΚΑΙ ΒΡΑΒΕΙΩΝ",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 133,
        "date": "Fri, 27/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-27T20:00:00",
        "title": "ΔΙΑΜΑΝΤΙΑ ΤΗΣ ΝΥΧΤΑΣ / DIAMONDS OF THE NIGHT / DEMANTY NOCI",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 134,
        "date": "Fri, 27/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-27T20:00:00",
        "title": "Ο ΘΑΝΑΤΟΣ ΤΟΥ ΝΤΙΚ ΛΟΝΓΚ / THE DEATH OF DICK ",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 135,
        "date": "Fri, 27/9",
        "time": "20:15",
        "director": "director goes here",
        "datetime": "1900-09-27T20:15:00",
        "title": "ΟΣΑ ΔΕΝ ΕΓΙΝΑΝ ΣΤΑΧΤΗ / LAND OF ASHES / CENIZA NEGRA",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 136,
        "date": "Fri, 27/9",
        "time": "20:15",
        "director": "director goes here",
        "datetime": "1900-09-27T20:15:00",
        "title": "ΜΗΤΕΡΑ / MOTHER",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 137,
        "date": "Fri, 27/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-27T20:30:00",
        "title": "ΠΑΒΑΡΟΤΙ / PAVAROTTI",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 138,
        "date": "Fri, 27/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-27T22:00:00",
        "title": "ΤΑ ΓΕΡΑΚΙΑ ΤΗΣ ΝΥΧΤΑΣ / BACURAU",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 139,
        "date": "Fri, 27/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-27T22:00:00",
        "title": "ΕΠΟΥΡΑΝΙΑ ΑΓΑΠΗ / DIVINE LOVE / DIVINO AMOR",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 140,
        "date": "Fri, 27/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-27T22:15:00",
        "title": "ΡΟΖ ΤΕΙΧΟΣ / PINK WALL",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 141,
        "date": "Fri, 27/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-27T22:30:00",
        "title": "ΤΑ ΧΡΟΝΙΚΑ ΤΗΣ ΜΑΡΙΟΝ ΣΤΟΟΥΚΣ / RECORDER: THE MARION STOKES PROJECT",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 142,
        "date": "Fri, 27/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-27T22:30:00",
        "title": "ΘΗΡΙΑ / ANIMALS",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 143,
        "date": "Fri, 27/9",
        "time": "23:00",
        "director": "director goes here",
        "datetime": "1900-09-27T23:00:00",
        "title": "ΟΛΑ ΓΙΑ ΤΟΝ ΙΒ / ALL ABOUT YVES / YVES",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 144,
        "date": "Sat, 28/9",
        "time": "17:15",
        "director": "director goes here",
        "datetime": "1900-09-28T17:15:00",
        "title": "ΕΚΕΙΝΗ ΤΗ ΜΕΡΑ, ΣΤΗΝ ΠΑΡΑΛΙΑ / THAT DAY, ON THE BEACH / HAI TAN DE YI TIAN",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 145,
        "date": "Sat, 28/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-28T17:30:00",
        "title": "Ο ΡΟΜΕΟΣ, Η ΙΟΥΛΙΕΤΑ ΚΑΙ ΤΑ ΣΚΟΤΑΔΙΑ / ROMEO, JULIET AND DARKNESS / ROMEO, JULIE A TMA",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 146,
        "date": "Sat, 28/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-28T18:00:00",
        "title": "ΟΙ ΔΡΟΜΟΙ ΤΗΣ ΚΑΡΔΙΑΣ / DRIVEWAYS",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 147,
        "date": "Sat, 28/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-28T18:00:00",
        "title": "Ο ΥΠΕΡΟΧΟΣ ΒΑΡΟΝΟΣ ΜΙΝΧΑΟΥΖΕΝ / THE FABULOUS BARON MUNCHAUSEN / BARON PRASIL",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 148,
        "date": "Sat, 28/9",
        "time": "18:15",
        "director": "director goes here",
        "datetime": "1900-09-28T18:15:00",
        "title": "Η ΤΕΧΝΗ ΤΟΥ ΚΙΝΗΜΑΤΟΓΡΑΦΙΚΟΥ ΗΧΟΥ / MAKING WAVES: THE ART OF CINEMATIC SOUND",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 149,
        "date": "Sat, 28/9",
        "time": "18:30",
        "director": "director goes here",
        "datetime": "1900-09-28T18:30:00",
        "title": "Η ΑΠΙΘΑΝΗ ΙΣΤΟΡΙΑ ΤΟΥ ΜΑΓΟΥ ΤΖΟΝΑΘΑΝ / THE AMAZING JOHNATHAN DOCUMENTARY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 150,
        "date": "Sat, 28/9",
        "time": "19:30",
        "director": "director goes here",
        "datetime": "1900-09-28T19:30:00",
        "title": "ELLA FITZGERALD: JUST ONE OF THOSE THINGS ",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 151,
        "date": "Sat, 28/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-28T20:00:00",
        "title": "ΖΗΤΕΙΤΑΙ ΠΑΡΘΕΝΑ ΓΙΑ ΘΥΣΙΑ / EXTRA ORDINARY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 152,
        "date": "Sat, 28/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-28T20:00:00",
        "title": "ΜΗΤΕΡΑ / MOTHER",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 153,
        "date": "Sat, 28/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-28T20:30:00",
        "title": "ΤΖΕΖΕΜΠΕΛ / JEZEBEL",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 154,
        "date": "Sat, 28/9",
        "time": "20:30",
        "director": "director goes here",
        "datetime": "1900-09-28T20:30:00",
        "title": "ΑΡΑΧΝΗ / SPIDER / ARANA",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 155,
        "date": "Sat, 28/9",
        "time": "20:45",
        "director": "director goes here",
        "datetime": "1900-09-28T20:45:00",
        "title": "ΦΩΤΙΑ ΣΤΗ ΛΟΥΙΖΙΑΝΑ / BURNING CANE",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 156,
        "date": "Sat, 28/9",
        "time": "21:45",
        "director": "director goes here",
        "datetime": "1900-09-28T21:45:00",
        "title": "Ο ΜΕΓΑΛΟΣ ΑΠΟΧΩΡΙΣΜΟΣ / SO LONG MY SON / DI JIU TIAN CHANG",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 157,
        "date": "Sat, 28/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-28T22:00:00",
        "title": "FARMING",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 158,
        "date": "Sat, 28/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-28T22:00:00",
        "title": "ΡΑΜΜΑΤΑ / STITCHES / SAVOVI",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 159,
        "date": "Sat, 28/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-28T22:30:00",
        "title": "Η ΑΝΑΦΟΡΑ ΓΙΑ ΤΟ ΠΑΡΤΙ ΚΑΙ ΤΟΥΣ ΚΑΛΕΣΜΕΝΟΥΣ / A REPORT ON THE PARTY AND GUESTS / O SLAVNOSTI A HOSTECH",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 160,
        "date": "Sat, 28/9",
        "time": "22:30",
        "director": "director goes here",
        "datetime": "1900-09-28T22:30:00",
        "title": "ZOMBI CHILD ",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 161,
        "date": "Sat, 28/9",
        "time": "23:00",
        "director": "director goes here",
        "datetime": "1900-09-28T23:00:00",
        "title": "ΕΛΑ ΣΤΟΝ ΜΠΑΜΠΑ / COME TO DADDY",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 162,
        "date": "Wed, 18/9",
        "time": "12:00",
        "director": "director goes here",
        "datetime": "1900-09-18T12:00:00",
        "title": "Εισιτήρια Διαρκείας : 10 Προβολών ",
        "subtitle": "subtitle goes here",
        "room": "Νύχτες Πρεμιέρας  - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 163,
        "date": "Wed, 18/9",
        "time": "12:00",
        "director": "director goes here",
        "datetime": "1900-09-18T12:00:00",
        "title": "Εισιτήρια Διαρκείας : 20 Προβολών",
        "subtitle": "subtitle goes here",
        "room": "Νύχτες Πρεμιέρας  - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 164,
        "date": "Sun, 29/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-29T17:30:00",
        "title": "ΒΡΑΒΕΥΜΕΝΕΣ ΤΑΙΝΙΕΣ ΜΙΚΡΟΥ ΜΗΚΟΥΣ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 165,
        "date": "Sun, 29/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-29T17:30:00",
        "title": "ΣΤΙΓΚ ΛΑΡΣΟΝ: Ο ΑΝΘΡΩΠΟΣ ΠΟΥ ΕΠΑΙΖΕ ΜΕ ΤΗ ΦΩΤΙΑ / STIEG LARSSON: THE MAN WHO PLAYED WITH FIRE / MANNEN SOM LEKTE MED ELD",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 166,
        "date": "Sun, 29/9",
        "time": "17:30",
        "director": "director goes here",
        "datetime": "1900-09-29T17:30:00",
        "title": "ΕΙΜΑΣΤΕ ΜΙΚΡΑ ΖΟΜΠΙ / WE ARE LITTLE ZOMBIES / WI A RITORU ZOMBIZU",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 167,
        "date": "Sun, 29/9",
        "time": "18:00",
        "director": "director goes here",
        "datetime": "1900-09-29T18:00:00",
        "title": "Η ΑΠΙΘΑΝΗ ΙΣΤΟΡΙΑ ΤΟΥ ΜΑΓΟΥ ΤΖΟΝΑΘΑΝ / THE AMAZING JOHNATHAN DOCUMENTARY",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 168,
        "date": "Sun, 29/9",
        "time": "18:15",
        "director": "director goes here",
        "datetime": "1900-09-29T18:15:00",
        "title": "ΔΕΝΤΡΑ ΣΤΗΝ ΕΡΗΜΟ / TALKING ABOUT TREES",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 169,
        "date": "Sun, 29/9",
        "time": "18:15",
        "director": "director goes here",
        "datetime": "1900-09-29T18:15:00",
        "title": "ΤΟ ΜΑΓΑΖΑΚΙ ΤΗΣ ΚΕΝΤΡΙΚΗΣ ΟΔΟΥ / THE SHOP ON MAIN STREET / OBCHOD NA KORZE",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 170,
        "date": "Sun, 29/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-29T19:45:00",
        "title": "ΠΡΟΒΟΛΗ ΒΡΑΒΕΥΜΕΝΗΣ ΤΑΙΝΙΑΣ",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 171,
        "date": "Sun, 29/9",
        "time": "19:45",
        "director": "director goes here",
        "datetime": "1900-09-29T19:45:00",
        "title": "H ΛΕΥΚΗ ΕΠΑΝΑΣΤΑΣΗ / MJOLK / THE COUNTY",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 172,
        "date": "Sun, 29/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-29T20:00:00",
        "title": "Η ΓΗ ΤΟΥ ΜΕΛΙΤΟΣ / HONEYLAND ",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 173,
        "date": "Sun, 29/9",
        "time": "20:00",
        "director": "director goes here",
        "datetime": "1900-09-29T20:00:00",
        "title": "ΦΙΛΟΘΕΗ, Η ΑΓΙΑ ΤΩΝ ΑΘΗΝΩΝ / PHILOTHEI, THE ATHENIAN SAINT",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 174,
        "date": "Sun, 29/9",
        "time": "20:15",
        "director": "director goes here",
        "datetime": "1900-09-29T20:15:00",
        "title": "ΠΑΙΧΝΙΔΙΑ ΤΗΣ ΤΥΧΗΣ / SERENDIPITY",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 175,
        "date": "Sun, 29/9",
        "time": "21:00",
        "director": "director goes here",
        "datetime": "1900-09-29T21:00:00",
        "title": "ΑΠΟΚΑΛΥΨΗ ΤΩΡΑ: FINAL CUT / APOCALYPSE NOW: FINAL CUT",
        "subtitle": "subtitle goes here",
        "room": "Κινηματογράφος ΙΝΤΕΑΛ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 176,
        "date": "Sun, 29/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-29T22:00:00",
        "title": "Η ΩΡΑ ΤΟΥ ΛΥΚΟΥ / THE WOLF HOUR",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 1 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 177,
        "date": "Sun, 29/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-29T22:00:00",
        "title": "ΤΟ ΤΕΛΟΣ ΤΗΣ ΔΙΑΔΡΟΜΗΣ / END OF SENTENCE",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 2 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 178,
        "date": "Sun, 29/9",
        "time": "22:00",
        "director": "director goes here",
        "datetime": "1900-09-29T22:00:00",
        "title": "Ο ΗΧΟΣ ΤΗΣ ΣΙΩΠΗΣ / THE SOUND OF SILENCE",
        "subtitle": "subtitle goes here",
        "room": "Κιν/φος ΑΣΤΟΡ - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 179,
        "date": "Sun, 29/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-29T22:15:00",
        "title": "ΔΙΑΜΑΝΤΙΑ ΤΗΣ ΝΥΧΤΑΣ / DIAMONDS OF THE NIGHT / DEMANTY NOCI",
        "subtitle": "subtitle goes here",
        "room": "Odeon Όπερα 2 - Αθήνα, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    },
    {
        "id": 180,
        "date": "Sun, 29/9",
        "time": "22:15",
        "director": "director goes here",
        "datetime": "1900-09-29T22:15:00",
        "title": "ΤΟ ΕΔΑΦΟΣ ΚΑΤΩ ΑΠΟ ΤΑ ΠΟΔΙΑ ΜΟΥ / THE GROUND BENEATH MY FEET / DER BODEN UNTER DEN FUSSEN",
        "subtitle": "subtitle goes here",
        "room": "Δαναός  - Δαναός 1 - Αμπελόκηποι, Αττική",
        "description": "description goes here",
        "isparty": "makeFalse",
        "isfirst": "makeFalse",
        "selected": "makeFalse"
    }
]