const movies = [
    {
        id: 0,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: true,
        selected: false
    },
    {
        id: 1,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 2,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 3,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 4,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 5,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "20 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 6,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: true,
        selected: false
    },
    {
        id: 7,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 8,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 9,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 10,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 11,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 12,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 13,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 14,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 15,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "21 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 16,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 17,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 18,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 19,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 20,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 21,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 22,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 23,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 24,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 25,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "22 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 26,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 27,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 28,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 29,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 30,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    },
    {
        id: 31,
        title: "The movie title",
        subtitle: "year/country/duration",
        room: "Cinema room 1",
        category: "category 1",
        director: "The director's name",
        datetime: "23 Sept 2019 17:00",
        description: "Spicy jalapeno bacon ipsum dolor amet short loin filet mignon landjaeger beef ribs turkey frankfurter swine jowl venison tongue bresaola boudin pork belly picanha. Ham hock flank buffalo jerky. Biltong shoulder pancetta, swine pork loin shankle kevin cupim ground round salami. Cow meatloaf landjaeger shankle, strip steak chicken ham pastrami fatback short loin. Brisket tri-tip turducken ribeye landjaeger, beef tongue ball tip strip steak bacon.",
        isparty: false,
        isfirst: false,
        selected: false
    }
];

export default movies;